Lexem = "lexem"
Lexem_class = "lexem_class"
Line_number = "line_number"
Position_number = "position_number"
Name = "name"
Type = "type"
Scope = "scope"

common_block = "COMMON_BLOCK"
while_block = "WHILE_BLOCK"
iterator_block = "ITERATOR_BLOCK"
iterator_start = "ITERATOR_START"
iterator_end = "ITERATOR_END"
for_block = "FOR_BLOCK"
if_block = "IF_BLOCK"
arithmetic_expression = "ARITHMETIC_EXPRESSION"
logical_expression = "LOGICAL_EXPRESSION"